### ISSUE TITLE
"mseng" is hardcoded in many urls

### ISSUE THREAD

**Issue by pradeepna** [khilan2goel/AnalyticsCollectors#1]

**Comment by pradeepna** [comment]
Orgname should be picked up from command line and used in URL. At most places mseng is hardcoded

**Comment by pradeepna** [comment]
@khilan2goel - I have a PR. Give me access to this and I will raise a PR. My gh name is pradeepna

**Comment by khilangoel** [comment]
Sorry @pradeepna . Should have changed it. Was testing it out with mseng, so hard corded it. I have given you permissions.

**Comment by khilangoel** [comment]
@pradeepna Did some refactoring. Fixed this as well.
