### ISSUE TITLE
There is an issue with ingestion. When I run the collector multiple times, multiple entries of the same entities are created

### ISSUE THREAD

**Issue by pradeepna** [khilan2goel/AnalyticsCollectors#2]
For this I had commented the code that prevents ingesting Release definition if the table already exists

![image](https://user-images.githubusercontent.com/17713256/70839037-be7c5600-1dbf-11ea-99fd-4757e94e00e3.png)

**Comment by khilangoel** [comment]
@pradeepna this happenes only when watermark table was not updated (as there is some latency in updation of watermarktable). Did you ran collector again just after few seconds? I was able to reproduce this when my watermark was still not updated and I ran the collector again?

**Comment by khilangoel** [comment]
Related to issue #3 . Closing this. WE need to run collectors after water mark table is updated. After atleast 5 minutes else duplicate entries can be created.
