### ISSUE TITLE
Watermark table does not seem to update to latest value

### ISSUE THREAD

**Issue by pradeepna** [khilan2goel/AnalyticsCollectors#3]
See the watermark table after ingestion. Watermark values are still the default values. 

![image](https://user-images.githubusercontent.com/17713256/70839057-e66bb980-1dbf-11ea-9a24-d2b992d2bfbe.png)

**Comment by khilangoel** [comment]
@pradeepna will look into this. I tried on mseng, didnt faced this issue. WIll look into this

**Comment by khilangoel** [comment]
@pradeepna This happens when rows are less than 50 for each entity, there is an issue in that case. Will raise the PR
